### ISSUE TITLE
How do you filter the shots?

### ISSUE THREAD

**Issue by jnoylinc** [aycatakmaz/wsvd_dataset_loader#2]
As written in the artical，I use the FlowNet2.0 to calculate the flow between the left and right frame.I think the horzontal flow is disparity.I caculate the number of  pixels with vertical disparity > 1 pixel. I found most of frame do not  meet this condition.I guess I have made some mistake. Could you give me some help?

**Comment by CJCHEN1230** [comment]
@jnoylinc  Hi, I recently try to make this WSVD dataset as well. The paper said the optical flow they used is only in the middle range of the picture since the corner usually restricted to large distortion.   I think that might be the answer.  By the way, I want to know how to do left right check from the output of flownet2. Does flownet2 generate two map( One is X disparity the other is Y)? Or how do you do the left right check with one optical flow image?

**Comment by aycatakmaz** [comment]
Hi,

Thank you for your interest in this codebase!

However, WSVD is not my project or my dataset, and unfortunately I am not working on it anymore. I only used the dataset back in the day when I used it for a project, and this repo only includes the helper scripts I have. I do not have further information about the details of this work.

Best,
Ayca
