### ISSUE TITLE
Could you provide the processed image pair?

### ISSUE THREAD

**Issue by CJCHEN1230** [aycatakmaz/wsvd_dataset_loader#3]
Hi, as my understanding, the original author provide the inference code and you provide the code for loading mp4 data. If I want rgb/depth pairs data from WSVD, I need to combine both of your code. Am i correct? Also, could you provide the processed data as the format of RGB/Depth image ?

**Comment by aycatakmaz** [comment]
Hi, I used this dataset for a personal research project of mine a few years ago. As the original repo back in the day did not provide the code needed to download the data, I had to write some dataset download code and simply shared the code also here on github. Maybe the original repo shares some scripts to download the data now - but I am not sure, as I switched to some other projects, and haven't been working on this project since then.
